export const cuisines = {
  american: "American",
  asian: "Asian",
  bbq: "BBQ",
  brazilian: "Brazilian",
  burger: "Burger",
  cafe: "Cafe",
  canjun: "Cajun",
  chinese: "Chinese",
  deli: "Deli",
  diner: "Diner",
  french: "French",
  fusion: "Fusion",
  greek: "Greek",
  healthyFood: "Healthy Food",
  indian: "Indian",
  irish: "Irish",
  italian: "Italian",
  japanese: "Japanese",
  latinAmerican: "Latin American",
  mediterranean: "Mediterranean",
  mexican: "Mexican",
  middleEastern: "Middle Eastern",
  mongolian: "Mongolian",
  pizza: "Pizza",
  sandwich: "Sandwich",
  seafood: "Seafood",
  southern: "Southern",
  southwestern: "Southwestern",
  steak: "Steak",
  sushi: "Sushi",
  taco: "Tapas",
  texmex: "Tex-Mex",
  thai: "Thai",
  turkish: "Turkish",
  vegitarian: "Vegitarian",
  vietnamese: "Vietnamese",
}
